gen-ent:
	go run -mod=mod entgo.io/ent/cmd/ent generate --template glob="./ent/template/*.tmpl" ./ent/schema
	@printf $(GREEN)"[SUCCESS] generate ent successfully"

gen-init:
	go run -mod=mod entgo.io/ent/cmd/ent init
	@printf $(GREEN)"[SUCCESS] generate ent successfully"

