version: '3'

services:
  #filebeat容器
  filebeat:
    image: elastic/filebeat:7.13.4
    container_name: filebeat
    environment:
      TZ: Asia/Shanghai
    user: root
    restart: always
    volumes:
      - ./deploy/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - iss_net
    depends_on:
      - kafka
  #zookeeper容器
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 2181:2181
    networks:
      - iss_net
      -
  #kafka容器
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - iss_net
    depends_on:
      - zookeeper

  #mysql容器
  mysql:
    image: mysql:8.0.24
    container_name: mysql
    environment:
      TZ: Asia/Shanghai

      MYSQL_ROOT_PASSWORD: PXDN93VRKUm8TeE7
    ports:
      - 33069:3306
    volumes:
      # 数据挂载
      - ./data/mysql/data:/var/lib/mysql
      # 日志
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - iss_net

  #redis容器
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 63799:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      # 数据文件
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass PXDN93VRKUm8TeE7  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - iss_net


networks:
  iss_net:
    driver: bridge
    #ipam:
    #  config:
    #    - subnet: 172.20.0.0/16

